var nameError = document.getElementById("name-error")
var emailError = document.getElementById("email-error")
var phoneError = document.getElementById("phone-error")
var messageError = document.getElementById("message-error")
var submitError = document.getElementById("submit-error")